# Generated by Django 4.0.3 on 2022-05-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Cnic',
            new_name='db_Cnic',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='DOB',
            new_name='db_DOB',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='FirstName',
            new_name='db_FirstName',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='LastName',
            new_name='db_LastName',
        ),
    ]
