# Generated by Django 4.0.3 on 2022-05-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rename_cnic_form_db_cnic_rename_dob_form_db_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Adress',
            new_name='db_Adress',
        ),
    ]
