# Generated by Django 4.0.3 on 2022-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_adress_form_db_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='db_FirstName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
