# Generated by Django 4.0.3 on 2022-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_form_db_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='db_Cnic',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
