# Generated by Django 4.0.3 on 2022-05-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_form_db_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='db_Adress',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='db_DOB',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='db_FirstName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='db_LastName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
