# Generated by Django 3.1.12 on 2022-07-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
