# Generated by Django 3.1.12 on 2022-07-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='db_city',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='db_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll',
            new_name='db_roll',
        ),
    ]
