# Generated by Django 3.1.12 on 2022-07-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20220727_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='db_roll',
            field=models.IntegerField(),
        ),
    ]
